### ISSUE TITLE
issue with keysControlDisabled=false

### ISSUE THREAD

**Issue by roman-telia** [maxmarinich/react-alice-carousel#117]
I have two ReactAliceCarousel instances on same page. they both have a window.onkeyup listener and when for instance space is pressed it performs an action. The other carousel reacts on that keypress as well, so when key is pressed in the second component the keyevent is also is fired as in the first component.

this problem can be fixed by addin event.stopPropagation(); in react-alice-carousel, to prevent this event from fiering in all instances.

**Comment by maxmarinich** [comment]
Hi, @roman-telia! Thank you for your comment. But this behavior is quite expected. The correct way to manage this case is to put the `keysControlDisabled={true} ' property in the second instance. This will not restrict the basic behavior.

**Comment by roman-telia** [comment]
but we can't then have ous users using keybboard controls in second carousel. we need this behaviour in both instances.

here is right way to fix this.

https://stackoverflow.com/questions/51794593/stop-event-propagation-from-input-in-react

**Comment by maxmarinich** [comment]
Your link not relevant for the issue. The behavior of the carousel is expected, because this is how js [works](https://developer.mozilla.org/ru/docs/Web/API/EventTarget/addEventListener). To handle your case you need:
1. Set `keysControlDisabled={true} ` for each instance
2. Assign `refs` for each instance
3. Handle the `keyup` event independently in the component that wrapped the instances
4. Create handle function for event listener, e.g.:
```js
// pseudo code
function handleKeyup(e) {
  if (/* first instance view === user view */) {
    if (e.code === 'ArrowRight') {
      this.firstInstanceRef.slideNext()
    }
  } else if (/* second instance view === user view */) {
    if (e.code === 'ArrowRight') {
      this.firstInstanceRef.slideNext()
    }
  }
}
```
