### ISSUE TITLE
Suggestion, Convert the build of the lib to use tsdx

### ISSUE THREAD

**Issue by felixmosh** [maxmarinich/react-alice-carousel#139]
[TSDX](https://github.com/formium/tsdx) is a wrapper around many tools for building modern libs, 
It supports out of the box TS, multi target bundles, babel best practices, tests with jest, github actions ci, ui playground.

I'm using it in 2 of the packages that I maintain and so far it is solving many pain.

I see that you are using gulp and many custom configs, would you accept a PR for this?

**Comment by maxmarinich** [comment]
Hi, @felixmosh! The current solution is a simple and working. But I was always open for more elegant solutions if they aren't redundant.

**Comment by Lateralus-lab** [comment]
If I turn on infinite mode for a slider, it creates cloned items in <li> elements. 
The problem is that cloned items aren't 100% height. The original cards are displaying correctly, but cloned ones aren't. 

Does anyone know how to solve this issue? I was playing with CSS for a bit with no luck. 

![carusel-issues](https://user-images.githubusercontent.com/59764339/117581568-600ef080-b0f5-11eb-86e2-813d33ff9454.png)

**Comment by maxmarinich** [comment]
Expired
