### ISSUE TITLE
Last slide rendered during SSR with `infinite` mode

### ISSUE THREAD

**Issue by Kerumen** [maxmarinich/react-alice-carousel#167]
I have a Gatsby blog with this library and the `infinite` prop. During SSR, the last slide is rendered inside the carousel and then changed back to the first slide when hydration occurs which makes the whole things flicker a bit. If I remove the `infinite` prop, it's working well.

I try to set up a repro as soon as possible!

This is my code:

```tsx
<ReactCarousel
  ref={ref}
  items={items}
  activeIndex={currentSlide}
  infinite
  mouseTracking
  disableDotsControls
  disableButtonsControls
  onSlideChanged={onSlideChanged}
/>
```

- react-alice-carousel version: `v2.2.1`

---

I found a workaround, I initialize a boolean to false and then I set it to true on the first render, this way `infinite` is false during SSR:

```tsx
const [isInfinite, setIsInfinite] = useState(false)

useEffect(() => {
  setIsInfinite(true)
}, [])

...

<ReactCarousel
  infinite={isInfinite}
/>
```

**Comment by maxmarinich** [comment]
Hi, @Kerumen! This is because the gallery can't get the styles when rendering on the server side. But from `v2.3` version it can handle the case use common css. 

__Client:__

<img width="1135" alt="Снимок экрана 2021-01-26 в 10 16 46" src="https://user-images.githubusercontent.com/9882979/105814879-1aee0500-5fc3-11eb-80f2-d110fd6ba40f.png">

__Server:__ has additionally class `__ssr`.

<img width="1431" alt="Снимок экрана 2021-01-26 в 10 18 03" src="https://user-images.githubusercontent.com/9882979/105814885-1de8f580-5fc3-11eb-8938-b996e1567233.png">


To handle flicker add next line at the root css file:
``` css
     .alice-carousel.__ssr .alice-carousel__stage-item:not(.__active) {
        display: none;
      }
```

**Comment by maxmarinich** [comment]
Hi @there! From v2.5.1 to enable css modifier set `ssrSilentMode` to false.
