### ISSUE TITLE
Images not rendering on AWS

### ISSUE THREAD

**Issue by pnbkn** [maxmarinich/react-alice-carousel#196]
I am using Gatsby, so hen I push to AWS, the LI widths in the carousel are changed to width="0" When I add width: 33% !important; the images show, but the carousel does not work. Works fine when I push to netlify.

**Comment by maxmarinich** [comment]
Hi, @pnbkn. I guess this issue is not related to the lib. Tested on  `gatsby v3.4.1` && base lib [sample](https://maxmarinich.github.io/react-alice-carousel/). Most likely the problem is in your code. Before open it again, please check yourself and provide code sample.

<img width="1433" alt="Снимок экрана 2021-05-12 в 8 09 32" src="https://user-images.githubusercontent.com/9882979/117921760-f6abff00-b2f9-11eb-908c-2ee9c82b73e7.png">
