### ISSUE TITLE
CSS: Parse error

### ISSUE THREAD

**Issue by JimOvermeen** [maxmarinich/react-alice-carousel#211]
Hi,

I use the Alice Carousel on my website. And after validating it on https://validator.w3.org/ i receive multiple CSS: Parse errors. I did not change the CSS. (see image)

![Screenshot 2021-09-17 at 14 05 05](https://user-images.githubusercontent.com/67960046/133780472-99707c33-deb4-4a8b-bef4-27b9336aa322.png)

Please let me know how this can be fixed

Thank you!

**Comment by maxmarinich** [comment]
Hi, @JimOvermeen! I guess this is not lib issue. And the problem is in your build config. I checked the [lib demo](https://maxmarinich.github.io/react-alice-carousel/) with tool you provided for me, please follow next link for verifying  [validator.w3.org](https://validator.w3.org/nu/?showoutline=yes&showimagereport=yes&doc=https%3A%2F%2Fmaxmarinich.github.io%2Freact-alice-carousel%2F).

**Comment by JimOvermeen** [comment]
Hi @maxmarinich ,

Thank you for your answer. We have fixed it in our build config.

Thank you!
