### ISSUE TITLE
Shows a piece of next slide

### ISSUE THREAD

**Issue by high-noroque** [maxmarinich/react-alice-carousel#46]
Upon rendering, the carousel shows a tiny piece of the next slide and right after its parent component's state changes, the image gets into place as desired. What can I do to fix this?
![caroosel](https://user-images.githubusercontent.com/29983269/51980068-95005780-2497-11e9-9dc4-a42206f4b3c8.gif)

![2019-02-01 13 41 05](https://user-images.githubusercontent.com/29983269/52121077-0e7a8000-2627-11e9-9e5b-fdba69d39116.png)

**Comment by maxmarinich** [comment]
Hi, @high-noroque! Please provide code sample or create a repo.

**Comment by high-noroque** [comment]
The function that fetches the array with pictures:
```export const fetchLeftCarousel = async () => {
       return [amazone, deutz, sicma, sola];};```

**Comment by maxmarinich** [comment]
@high-noroque, the Carousel works like expected. You have bad a component architecture.  Every time the gallery gets new items and run recalculation, because you call method `this.renderImages` in the render, which returns a new object.
`First`, you should provide real code sample. It's hard to writing a code from your image screen. Use sandbox [ AliceCarousel live demo](https://codesandbox.io/s/vq1y9z3x80)
`Secondly`, you should refactor the code, e.g (it's example only, it's not gracefully): 
```js
class TopCarousel extends React.Component {
  state = {
    pictures: [],
  }

  componentDidMount() {
    this.props.fetchPictures().then((result) => {
      const pictures = this.renderImages(result)
      this.setState({ pictures })
    })
  }

  renderImages(pictures = []) {
    return pictures.map((picture) => {
      return <img key={picture} src={picture} alt="" />
    })
  }

  render() {
    return (
      <AliceCarousel 
        items={this.state.pictures}
        // ...rest props
      />
    )
  }
}

```
